### ISSUE TITLE
Not able to run phpunit

### ISSUE THREAD

**Issue by RajeshHegde** [Vinelab/cdn#46]
I'm have done some modification to support caching support. But Travis test fails because of the following reason:

PHP Fatal error:  Cannot redeclare any() (previously declared in /home/travis/build/Vinelab/cdn/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php:395) in /home/travis/build/Vinelab/cdn/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 59

If you are also getting similar error, please share your feedback on this issue.

**Comment by Mahmoudz** [comment]
@RajeshHegde yes that's true, sorry for the delay, I didn't have time previously to check on this package.
I was checking this error today, and I found out that this is caused by the update of `mockery/mockery` from `0.9.3` to `0.9.4` is it requires the `hamcrest/hamcrest-php 1.2.2` which causes this error.
I havn’t tried to debug it now for the mean time I just required the version `0.9.3` of mockery in the package composer which solves the problem.
I will be checking your changes and merging them today if everything is cool.
Thanks again for your interest.
